name: Publish

on:
  push:
    tags:
      - "v*.*.*" # triggers on tags like v1.0.0
  workflow_dispatch: # allows manual trigger from the Actions tab

jobs:
  publish:
    permissions:
      contents: write # <-- required to create releases/upload assets
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Configure node-gyp for MSVC (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          echo "npm_config_msvs_version=2022" >> $env:GITHUB_ENV
          echo "GYP_MSVS_VERSION=2022" >> $env:GITHUB_ENV
          echo "npm_config_build_from_source=false" >> $env:GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      # Rebuild native modules (e.g. better-sqlite3) against the specific Electron version
      - name: Rebuild native modules for Electron
        run: npx @electron/rebuild

      - name: Publish
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
